version: 1
formatters:
  brief:
    format: "%(asctime)s - %(message)s"
  simple:
    format: "%(asctime)s - %(threadName)s - %(filename)s - %(lineno)d - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
  debugFile:
    class: logging.FileHandler
    formatter: simple
    level: DEBUG
    filename: ./log/debug.log
    encoding: utf8
  infoFile:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ./log/info.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  errorFile:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ./log/error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  warningFile:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: simple
    filename: ./log/warn.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  main:
    level: DEBUG
    handlers: [ console, debugFile, infoFile, errorFile,warningFile ]
#root:
#  level: DEBUG
#  handlers: [ console ]